---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bridgepdccom/public_html/bridge
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R favicon.ico $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R flyer $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
